from .user import User
from .student import Student
from .teacher import Teacher
from .parent import Parent
from .management import Management
from .class_model import Class
from .subject import Subject
from .attendance import Attendance
from .homework import Homework
from .exam import Exam
from .mark import Mark
from .notification import Notification
from .salary import Salary
from .ai_log import AILog
